package com.example.taskcatalog.repository

import com.example.taskcatalog.model.Task
import com.example.taskcatalog.model.TaskStatus
import java.time.LocalDateTime
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest
import org.springframework.context.annotation.Import
import org.springframework.jdbc.core.JdbcTemplate

@JdbcTest
@Import(JdbcTaskRepository::class)
class JdbcTaskRepositoryTest {

    @Autowired
    lateinit var jdbcTemplate: JdbcTemplate

    @Autowired
    lateinit var repository: JdbcTaskRepository

    @BeforeEach
    fun setUpSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS tasks")
        jdbcTemplate.execute(
            """
            CREATE TABLE tasks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(100) NOT NULL,
                description VARCHAR(1000),
                status VARCHAR(30) NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
            """.trimIndent(),
        )
    }

    @Test
    fun `save persists task and findById maps it back`() {
        val createdAt = LocalDateTime.of(2026, 3, 26, 12, 0, 0)
        val task = Task(
            id = null,
            title = "Prepare report",
            description = "Monthly financial report",
            status = TaskStatus.NEW,
            createdAt = createdAt,
            updatedAt = createdAt,
        )

        val savedTask = repository.save(task)
        val loadedTask = repository.findById(requireNotNull(savedTask.id))

        assertNotNull(savedTask.id)
        assertEquals("Prepare report", loadedTask?.title)
        assertEquals("Monthly financial report", loadedTask?.description)
        assertEquals(TaskStatus.NEW, loadedTask?.status)
        assertEquals(createdAt, loadedTask?.createdAt)
        assertEquals(createdAt, loadedTask?.updatedAt)
    }

    @Test
    fun `findAll applies status filter pagination and descending createdAt sorting`() {
        insertTask(101L, "Old NEW", TaskStatus.NEW, LocalDateTime.of(2026, 3, 20, 10, 0, 0))
        insertTask(102L, "Newest NEW", TaskStatus.NEW, LocalDateTime.of(2026, 3, 22, 10, 0, 0))
        insertTask(103L, "In progress", TaskStatus.IN_PROGRESS, LocalDateTime.of(2026, 3, 21, 10, 0, 0))
        insertTask(104L, "Middle NEW", TaskStatus.NEW, LocalDateTime.of(2026, 3, 21, 12, 0, 0))

        val firstPage = repository.findAll(page = 0, size = 2, status = TaskStatus.NEW)
        val secondPage = repository.findAll(page = 1, size = 2, status = TaskStatus.NEW)

        assertEquals(listOf("Newest NEW", "Middle NEW"), firstPage.map { it.title })
        assertEquals(listOf("Old NEW"), secondPage.map { it.title })
        assertEquals(3L, repository.count(TaskStatus.NEW))
        assertEquals(4L, repository.count(null))
    }

    @Test
    fun `updateStatus updates only status and updatedAt`() {
        val createdAt = LocalDateTime.of(2026, 3, 26, 12, 0, 0)
        val updatedAt = LocalDateTime.of(2026, 3, 27, 9, 30, 0)
        insertTask(201L, "Review PR", TaskStatus.NEW, createdAt)

        val affectedRows = repository.updateStatus(201L, TaskStatus.DONE, updatedAt)
        val updatedTask = repository.findById(201L)

        assertEquals(1, affectedRows)
        assertEquals("Review PR", updatedTask?.title)
        assertEquals(TaskStatus.DONE, updatedTask?.status)
        assertEquals(createdAt, updatedTask?.createdAt)
        assertEquals(updatedAt, updatedTask?.updatedAt)
    }

    @Test
    fun `deleteById removes task`() {
        insertTask(301L, "Archive invoices", TaskStatus.DONE, LocalDateTime.of(2026, 3, 24, 16, 0, 0))

        val affectedRows = repository.deleteById(301L)

        assertEquals(1, affectedRows)
        assertNull(repository.findById(301L))
    }

    private fun insertTask(
        id: Long,
        title: String,
        status: TaskStatus,
        createdAt: LocalDateTime,
    ) {
        jdbcTemplate.update(
            """
            INSERT INTO tasks (id, title, description, status, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?)
            """.trimIndent(),
            id,
            title,
            "$title description",
            status.name,
            createdAt,
            createdAt,
        )
    }
}
